export const DECORATORS_PREFIX = 'swagger';
export const DECORATORS = {
    API_OPERATION: `${DECORATORS_PREFIX}/apiOperation`,
    API_RESPONSE: `${DECORATORS_PREFIX}/apiResponse`,
    API_PRODUCES: `${DECORATORS_PREFIX}/apiProduces`,
    API_CONSUMES: `${DECORATORS_PREFIX}/apiConsumes`,
    API_USE_TAGS: `${DECORATORS_PREFIX}/apiUseTags`,
    API_PARAMETERS: `${DECORATORS_PREFIX}/apiParameters`,
    API_MODEL_PROPERTIES: `${DECORATORS_PREFIX}/apiModelProperties`,
    API_MODEL_PROPERTIES_ARRAY: `${DECORATORS_PREFIX}/apiModelPropertiesArray`,
    API_BEARER: `${DECORATORS_PREFIX}/apiBearer`,
    API_OAUTH2: `${DECORATORS_PREFIX}/apiOauth2`,
};