import { head } from 'es-toolkit/compat';
import { isAbsolute, posix } from 'path';
import * as ts from 'typescript';
import { PluginOptions } from '../merge-options.js';
import {
  getDecoratorName,
  getText,
  getTypeArguments,
  hasFlag,
  isArray,
  isBigInt,
  isBoolean,
  isEnum,
  isInterface,
  isNumber,
  isString,
  isStringLiteral,
  isStringMapping
} from './ast-utils.js';

export function getDecoratorOrUndefinedByNames(
  names: string[],
  decorators: readonly ts.Decorator[],
  factory: ts.NodeFactory
): ts.Decorator | undefined {
  return (decorators || factory.createNodeArray()).find((item) => {
    try {
      const decoratorName = getDecoratorName(item);
      return names.includes(decoratorName);
    } catch {
      return false;
    }
  });
}

export function getTypeReferenceAsString(
  type: ts.Type,
  typeChecker: ts.TypeChecker,
  arrayDepth = 0
): {
  typeName: string;
  isArray?: boolean;
  arrayDepth?: number;
} {
  if (isArray(type)) {
    const arrayType = getTypeArguments(type)[0];
    const { typeName, arrayDepth: depth } = getTypeReferenceAsString(
      arrayType,
      typeChecker,
      arrayDepth + 1
    );
    if (!typeName) {
      return { typeName: undefined };
    }
    return {
      typeName: `${typeName}`,
      isArray: true,
      arrayDepth: depth
    };
  }
  if (isBoolean(type)) {
    return { typeName: Boolean.name, arrayDepth };
  }
  if (isNumber(type)) {
    return { typeName: Number.name, arrayDepth };
  }
  if (isBigInt(type)) {
    return { typeName: BigInt.name, arrayDepth };
  }
  if (isString(type) || isStringLiteral(type) || isStringMapping(type)) {
    return { typeName: String.name, arrayDepth };
  }
  if (isPromiseOrObservable(getText(type, typeChecker))) {
    const typeArguments = getTypeArguments(type);
    const elementType = getTypeReferenceAsString(
      head(typeArguments),
      typeChecker,
      arrayDepth
    );
    return elementType;
  }
  if (type.isClass()) {
    return { typeName: getText(type, typeChecker), arrayDepth };
  }
  try {
    const text = getText(type, typeChecker);
    if (text === Date.name) {
      return { typeName: text, arrayDepth };
    }
    if (isOptionalBoolean(text)) {
      return { typeName: Boolean.name, arrayDepth };
    }
    if (
      isAutoGeneratedTypeUnion(type) ||
      isAutoGeneratedEnumUnion(type, typeChecker)
    ) {
      const types = (type as ts.UnionOrIntersectionType).types;
      return getTypeReferenceAsString(
        types[types.length - 1],
        typeChecker,
        arrayDepth
      );
    }
    if (
      text === 'any' ||
      text === 'unknown' ||
      text === 'object' ||
      isInterface(type) ||
      (type.isUnionOrIntersection() && !isEnum(type))
    ) {
      return { typeName: 'Object', arrayDepth };
    }
    if (isEnum(type)) {
      return { typeName: undefined, arrayDepth };
    }
    if (type.aliasSymbol) {
      return { typeName: 'Object', arrayDepth };
    }
    if (
      typeChecker.getApparentType(type).getSymbol().getEscapedName() ===
      'String'
    ) {
      return { typeName: String.name, arrayDepth };
    }
    return { typeName: undefined };
  } catch {
    return { typeName: undefined };
  }
}

/**
 * Returns `true` when the supplied type text refers to a top-level
 * `Promise<...>` or `Observable<...>` instantiation.
 *
 * The match is anchored to the start of the string (or to a fully qualified
 * `import("...").` prefix) so user-defined classes whose names happen to end
 * with `Promise` / `Observable` (for example `MyPromise<T>` or
 * `AsyncObservable<T>`) are not mistakenly unwrapped to their inner type
 * argument.
 */
export function isPromiseOrObservable(type: string) {
  return /(^|\.)(Promise|Observable)</.test(type);
}

export function hasPropertyKey(
  key: string,
  properties: ts.NodeArray<ts.PropertyAssignment>
): boolean {
  return properties
    .filter((item) => !isDynamicallyAdded(item))
    .some((item) => item.name.getText() === key);
}

export function getOutputExtension(fileName: string): string {
  if (fileName.endsWith('.mts')) {
    return '.mjs';
  } else if (fileName.endsWith('.cts')) {
    return '.cjs';
  } else {
    return '.js';
  }
}

export function replaceImportPath(
  typeReference: string,
  fileName: string,
  options: PluginOptions
) {
  if (!typeReference.includes('import')) {
    return { typeReference, importPath: null };
  }

  if (options.esmCompatible) {
    typeReference = typeReference.replace(
      ', { with: { "resolution-mode": "import" } }',
      ''
    );
  }

  let importPath = /\(\"([^)]).+(\")/.exec(typeReference)[0];
  if (!importPath) {
    return { typeReference: undefined, importPath: null };
  }
  importPath = convertPath(importPath);
  importPath = importPath.slice(2, importPath.length - 1);

  // Decode any URL-encoded characters (e.g. non-ASCII) that TypeScript may
  // have introduced in the import path so that posix.relative can correctly
  // compute a relative path against the (non-encoded) file name.
  const decodedImportPath = safeDecodeURIComponent(importPath);

  try {
    if (isAbsolute(decodedImportPath)) {
      throw {};
    }

    require.resolve(decodedImportPath);
    if (!options.esmCompatible) {
      typeReference = typeReference.replace('import', 'require');
    }

    return {
      typeReference,
      importPath: null
    };
  } catch {
    const from = options?.readonly
      ? safeDecodeURIComponent(convertPath(options.pathToSource))
      : getOutputDir(fileName, options);

    const targetPath =
      options.outDir &&
      options.rootDir &&
      decodedImportPath.startsWith(convertPath(options.rootDir))
        ? posix.join(
            convertPath(options.outDir),
            posix.relative(convertPath(options.rootDir), decodedImportPath)
          )
        : decodedImportPath;
    let relativePath = posix.relative(from, targetPath);
    relativePath = relativePath[0] !== '.' ? './' + relativePath : relativePath;

    const normalizedPath = normalizePackagePath(relativePath);
    if (normalizedPath !== relativePath) {
      relativePath = normalizedPath;
    } else if (options.esmCompatible) {
      // Add appropriate extension for non-node_modules imports
      const extension = getOutputExtension(fileName);
      relativePath += extension;
    }

    typeReference = typeReference.replace(importPath, relativePath);

    if (options.readonly) {
      const { typeName, typeImportStatement } =
        convertToAsyncImport(typeReference);
      return {
        typeReference: typeImportStatement,
        typeName,
        importPath: relativePath
      };
    }

    if (options.esmCompatible) {
      const { typeName, typeImportStatement } =
        convertToAsyncImport(typeReference);
      return {
        typeReference: `(${typeImportStatement}).${typeName}`,
        importPath: relativePath
      };
    }

    return {
      typeReference: typeReference.replace('import', 'require'),
      importPath: relativePath
    };
  }
}

/**
 * Returns the directory from which the generated require()/import() call will
 * execute at runtime.  When tsconfig specifies outDir+rootDir the output file
 * lives at a different path depth than the source file, so we rebase the
 * source directory onto the output tree before computing relative import paths.
 */
function getOutputDir(fileName: string, options: PluginOptions): string {
  const sourceDir = posix.dirname(
    safeDecodeURIComponent(convertPath(fileName))
  );
  if (options.outDir && options.rootDir) {
    const outDir = convertPath(options.outDir);
    const rootDir = convertPath(options.rootDir);
    return posix.join(outDir, posix.relative(rootDir, sourceDir));
  }
  return sourceDir;
}

function convertToAsyncImport(typeReference: string) {
  const regexp = /import\(.+\).([^\]]+)(\])?/;
  const match = regexp.exec(typeReference);

  if (match?.length >= 2) {
    const importPos = typeReference.indexOf(match[0]);
    typeReference = typeReference.replace(`.${match[1]}`, '');

    return {
      typeImportStatement: insertAt(typeReference, importPos, 'await '),
      typeName: match[1]
    };
  }

  return { typeImportStatement: typeReference };
}

export function insertAt(string: string, index: number, substring: string) {
  return string.slice(0, index) + substring + string.slice(index);
}

export function isDynamicallyAdded(identifier: ts.Node) {
  return identifier && !identifier.parent && identifier.pos === -1;
}

/**
 * When "strict" mode enabled, TypeScript transform the enum type to a union composed of
 * the enum values and the undefined type. Hence, we have to lookup all the union types to get the original type
 * @param type
 * @param typeChecker
 */
export function isAutoGeneratedEnumUnion(
  type: ts.Type,
  typeChecker: ts.TypeChecker
): ts.Type {
  if (type.isUnionOrIntersection() && !isEnum(type)) {
    if (!type.types) {
      return undefined;
    }
    const undefinedTypeIndex = type.types.findIndex(
      (type: any) =>
        type.intrinsicName === 'undefined' || type.intrinsicName === 'null'
    );
    if (undefinedTypeIndex < 0) {
      return undefined;
    }

    // "strict" mode for enums
    let parentType = undefined;
    const isParentSymbolEqual = type.types.every((item, index) => {
      if (index === undefinedTypeIndex) {
        return true;
      }
      if (!item.symbol) {
        return false;
      }
      if (
        !(item.symbol as any).parent ||
        item.symbol.flags !== ts.SymbolFlags.EnumMember
      ) {
        return false;
      }
      const symbolType = typeChecker.getDeclaredTypeOfSymbol(
        (item.symbol as any).parent
      );
      if (symbolType === parentType || !parentType) {
        parentType = symbolType;
        return true;
      }
      return false;
    });
    if (isParentSymbolEqual) {
      return parentType;
    }
  }
  return undefined;
}

/**
 * when "strict" mode enabled, TypeScript transform the type signature of optional properties to
 * the {undefined | T} where T is the original type. Hence, we have to extract the last type of type union
 * @param type
 */
export function isAutoGeneratedTypeUnion(type: ts.Type): boolean {
  if (type.isUnionOrIntersection() && !isEnum(type)) {
    if (!type.types) {
      return false;
    }
    const undefinedTypeIndex = type.types.findIndex(
      (type: any) => type.intrinsicName === 'undefined'
    );

    // "strict" mode for non-enum properties
    if (type.types.length === 2 && undefinedTypeIndex >= 0) {
      return true;
    }
  }
  return false;
}

function isPlainStringLiteralType(type: ts.Type): type is ts.StringLiteralType {
  return (
    isStringLiteral(type) &&
    !(type.symbol && (type.symbol.flags & ts.SymbolFlags.EnumMember) !== 0)
  );
}

function isPlainNumberLiteralType(type: ts.Type): type is ts.NumberLiteralType {
  return (
    hasFlag(type, ts.TypeFlags.NumberLiteral) &&
    !(type.symbol && (type.symbol.flags & ts.SymbolFlags.EnumMember) !== 0)
  );
}

/**
 * Returns the literal values from a union type like `'a' | 'b'` or `1 | 2`,
 * stripping null/undefined constituents.
 * All non-null/undefined constituents must be the same kind of literal
 * (all string or all number). TypeScript enum members are excluded.
 */
export function getStringLiteralUnionValues(
  type: ts.Type
): { values: (string | number)[]; isNullable: boolean } | undefined {
  if (!type.isUnion()) {
    return undefined;
  }
  const isNullable = type.types.some((t) => hasFlag(t, ts.TypeFlags.Null));

  const members = type.types.filter(
    (t) => !hasFlag(t, ts.TypeFlags.Null) && !hasFlag(t, ts.TypeFlags.Undefined)
  );

  if (members.length === 0) {
    return undefined;
  }

  if (members.every(isPlainStringLiteralType)) {
    return { values: members.map((t) => t.value), isNullable };
  }

  if (members.every(isPlainNumberLiteralType)) {
    return { values: members.map((t) => t.value), isNullable };
  }

  return undefined;
}

export function extractTypeArgumentIfArray(type: ts.Type) {
  if (isArray(type)) {
    type = getTypeArguments(type)[0];
    if (!type) {
      return undefined;
    }
    return {
      type,
      isArray: true
    };
  }
  return {
    type,
    isArray: false
  };
}

/**
 * when "strict" mode enabled, TypeScript transform optional boolean properties to "boolean | undefined"
 * @param text
 */
function isOptionalBoolean(text: string) {
  return typeof text === 'string' && text === 'boolean | undefined';
}

/**
 * Converts Windows specific file paths to posix
 * @param windowsPath
 */
export function convertPath(windowsPath: string) {
  return windowsPath
    .replace(/^\\\\\?\\/, '')
    .replace(/\\/g, '/')
    .replace(/\/\/+/g, '/');
}

/**
 * Safely decodes URL-encoded characters in a path (e.g. non-ASCII characters
 * that TypeScript may encode when generating type reference strings).
 * Returns the original string if decoding fails.
 * @param path
 */
export function safeDecodeURIComponent(path: string) {
  try {
    return decodeURIComponent(path);
  } catch {
    return path;
  }
}

/**
 * When a path goes through node_modules (e.g. a workspace package resolved to
 * its physical location inside node_modules), strip the node_modules prefix so
 * the generated import uses the package specifier instead of a relative path.
 * This mirrors the same normalisation already done inside replaceImportPath().
 *
 * For example:
 *   ../node_modules/@amk/utils/src/dto/order.dto  →  @amk/utils/src/dto/order.dto
 *   ../../../packages/product-warehouse/dist/index  (no node_modules) → unchanged
 */
export function normalizePackagePath(importPath: string): string {
  const nodeModulesText = 'node_modules';
  const nodeModulePos = importPath.indexOf(nodeModulesText);
  if (nodeModulePos < 0) {
    return importPath;
  }

  let packagePath = importPath.slice(
    nodeModulePos + nodeModulesText.length + 1 // skip the trailing slash
  );

  const typesText = '@types';
  const typesPos = packagePath.indexOf(typesText);
  if (typesPos >= 0) {
    packagePath = packagePath.slice(typesPos + typesText.length + 1);
  }

  const indexText = '/index';
  const indexPos = packagePath.indexOf(indexText);
  if (indexPos >= 0) {
    packagePath = packagePath.slice(0, indexPos);
  }

  return packagePath;
}

/**
 * Checks if a node can be directly referenced.
 * In the readonly mode, only literals can be referenced directly.
 * Nodes like identifiers or call expressions are not available in the auto-generated code.
 */
export function canReferenceNode(node: ts.Node, options: PluginOptions) {
  if (!options.readonly) {
    return true;
  }
  if (ts.isCallExpression(node) || ts.isIdentifier(node)) {
    return false;
  }
  if (ts.isNewExpression(node)) {
    if ((node.expression as ts.Identifier)?.escapedText === 'Date') {
      return true;
    }
    return false;
  }
  if (
    node.kind === ts.SyntaxKind.FalseKeyword ||
    node.kind === ts.SyntaxKind.TrueKeyword ||
    node.kind === ts.SyntaxKind.NullKeyword
  ) {
    return true;
  }
  if (
    ts.isNumericLiteral(node) ||
    ts.isPrefixUnaryExpression(node) ||
    ts.isStringLiteral(node)
  ) {
    return true;
  }
  return false;
}
